---
- name: Install plex
  hosts: plex

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Mount media drive from NAS
      become: true
      ansible.posix.mount:
        src: //10.0.30.10/Media
        path: /home/josh/media
        opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
        fstype: cifs
        state: mounted

    - name: Install plex
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: plex
        tailscale_container_image: lscr.io/linuxserver/plex
        tailscale_container_tag: arm64v8-latest
        tailscale_container_https_container: true
        tailscale_container_serve_port: 32400
        tailscale_container_userspace_networking: "false"
        tailscale_container_public: true
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/plex/config:/config
          - /home/{{ ansible_user }}/media/media:/media
        tailscale_container_env_vars:
          PUID: "1000"
          PGID: "999"
          TZ: "America/New_York"
          Version: "docker"
        tailscale_container_labels:
          nautical-backup.enable: "true"
...
