---
- name: Install Authentik
  hosts: authentik
  vars:
    authentik_version: 2024.10.0

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"
    
    - name: Ensure templates folder has correct permissions
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/authentik-server/custom-templates
        state: directory
        owner: 1000
        group: "docker"
        mode: "0775"

    - name: Ensure media folder has correct permissions
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/authentik-server/media
        state: directory
        owner: 1000
        group: "docker"
        mode: "0775"

    - name: Ensure certs folder has correct permissions
      become: true
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/authentik-worker/certs
        state: directory
        owner: 1000
        group: "docker"
        mode: "0775"

    - name: Install Authentik DB
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_no_serve: true
        tailscale_container_service_name: authentik-db
        tailscale_container_image: docker.io/library/postgres
        tailscale_container_tag: 16-alpine
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/authentik-db/data:/var/lib/postgresql/data
        tailscale_container_env_vars:
          POSTGRES_PASSWORD: "{{ AUTHENTIK_DB_PASS }}"
          POSTGRES_USER: "{{ AUTHENTIK_DB_USER }}"
          POSTGRES_DB: "{{ AUTHENTIK_DB_NAME }}"
        tailscale_container_labels:
          nautical-backup.enable: "true"
          
    - name: Install Redis
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_no_serve: true
        tailscale_container_service_name: authentik-redis
        tailscale_container_image: docker.io/library/redis
        tailscale_container_tag: alpine
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/authentik-redis/data:/data
        tailscale_container_commands: --save 60 1 --loglevel warning
        tailscale_container_labels:
          nautical-backup.enable: "true"

    - name: Install Authentik server
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: authentik-server
        tailscale_container_image: ghcr.io/goauthentik/server
        tailscale_container_tag: "{{ authentik_version }}"
        tailscale_container_commands: server
        tailscale_container_userspace_networking: "false"
        tailscale_container_serve_port: 9000
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/authentik-server/media:/media
          - /home/{{ ansible_user }}/authentik-server/custom-templates:/templates
        tailscale_container_env_vars:
          AUTHENTIK_REDIS__HOST: authentik-redis.{{ tailnet_name }}
          AUTHENTIK_POSTGRESQL__HOST: authentik-db.{{ tailnet_name }}
          AUTHENTIK_POSTGRESQL__USER: "{{ AUTHENTIK_DB_USER }}"
          AUTHENTIK_POSTGRESQL__NAME: "{{ AUTHENTIK_DB_NAME }}"
          AUTHENTIK_POSTGRESQL__PASSWORD: "{{ AUTHENTIK_DB_PASS }}"
          AUTHENTIK_SECRET_KEY: "{{ AUTHENTIK_SECRET_KEY }}"
          AUTHENTIK_ERROR_REPORTING_ENABLED: "true"
          AUTHENTIK_EMAIL__HOST: smtp.gmail.com
          AUTHENTIK_EMAIL__PORT: "587"
          AUTHENTIK_EMAIL__FROM: authentik@nollhome.casa
          AUTHENTIK_EMAIL__USE_TLS: "true"
          AUTHENTIK_EMAIL__USERNAME: "{{ gmail_address }}"
          AUTHENTIK_EMAIL__PASSWORD: "{{ gmail_app_pass }}"

        tailscale_container_labels: 
          nautical-backup.enable: "true"
          traefik.enable: "true"
          # Authentik traefik service 
          traefik.http.services.authentik-svc.loadbalancer.server.scheme: "http"
          traefik.http.services.authentik-svc.loadbalancer.server.port: "9000"
          # Router for Authentik web page
          traefik.http.routers.authentik-server.rule: "Host(`authentik.{{ domain_name }}`)"
          traefik.http.routers.authentik-server.entrypoints: "https"
          traefik.http.routers.authentik-server.tls: "true"
          traefik.http.routers.authentik-server.tls.certresolver: "cloudflare"
          traefik.http.routers.authentik-server.service: "authentik-svc"
          # Router for Authentik forward auth redirects
          traefik.http.routers.authentik-forwardauth-redirect.rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.{{ domain_name }}`) && PathPrefix(`/outpost.goauthentik.io/`)"
          traefik.http.routers.authentik-forwardauth-redirect.entrypoints: "https"
          traefik.http.routers.authentik-forwardauth-redirect.tls: "true"
          traefik.http.routers.authentik-forwardauth-redirect.tls.certresolver: "cloudflare"
          traefik.http.routers.authentik-forwardauth-redirect.service: "authentik-svc"

    - name: Install Authentik worker
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_no_serve: true
        tailscale_container_service_name: authentik-worker
        tailscale_container_image: ghcr.io/goauthentik/server
        tailscale_container_tag: "{{ authentik_version }}"
        tailscale_container_commands: worker
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/authentik-server/media:/media
          - /home/{{ ansible_user }}/authentik-server/custom-templates:/templates
          - /home/{{ ansible_user }}/authentik-worker/certs:/certs
        tailscale_container_env_vars:
          AUTHENTIK_REDIS__HOST: authentik-redis.{{ tailnet_name }}
          AUTHENTIK_POSTGRESQL__HOST: authentik-db.{{ tailnet_name }}
          AUTHENTIK_POSTGRESQL__USER: "{{ AUTHENTIK_DB_USER }}"
          AUTHENTIK_POSTGRESQL__NAME: "{{ AUTHENTIK_DB_NAME }}"
          AUTHENTIK_POSTGRESQL__PASSWORD: "{{ AUTHENTIK_DB_PASS }}"
          AUTHENTIK_SECRET_KEY: "{{ AUTHENTIK_SECRET_KEY }}"
          AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
          AUTHENTIK_EMAIL__HOST: smtp.gmail.com
          AUTHENTIK_EMAIL__PORT: "587"
          AUTHENTIK_EMAIL__FROM: authentik@nollhome.casa
          AUTHENTIK_EMAIL__USE_TLS: "true"
          AUTHENTIK_EMAIL__USERNAME: "{{ gmail_address }}"
          AUTHENTIK_EMAIL__PASSWORD: "{{ gmail_app_pass }}"
        tailscale_container_labels:
          nautical-backup.enable: "true"