---
- name: Install Docker, Portainer, and Nautical Backup
  hosts: docker

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/vars"

    - name: Run Docker setup role
      ansible.builtin.include_role:
        name: joshrnoll.homelab.docker_setup
      vars:
        docker_setup_tailscale_oauth_client_secret: "{{ tailscale_conatiners_oauth_client['secret'] }}"
        docker_setup_nas_ip_or_hostname: truenas.mink-pirate.ts.net
        docker_setup_share_name: DockerBackups
        docker_setup_mount_path: /home/{{ ansible_user }}/dockerbackups
        docker_setup_share_username: "{{ truenas_username }}"
        docker_setup_share_password: "{{ truenas_password }}"
...
