---
- name: Deploy {{ deploy_container_service_name }}
  hosts: "{{ deploy_container_host_group_name }}"
  vars:
    deploy_container_service_name: kavita # Service/container name
    deploy_container_host_group_name: kavita # Host group for container to be deployed to
    deploy_container_service_image: jvmilazz0/kavita # Container image -- ex. louislam/uptime-kuma
    deploy_container_service_tag: latest # Image tag -- ex. latest
    deploy_container_service_port: "5000" # Must be quoted -- ex. "80" not 80
    deploy_container_service_scheme: http # http or https
    deploy_container_forward_auth: false # true or false
    deploy_container_tailnet_name: "{{ tailnet_name }}"
    deploy_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
    deploy_container_domain_name: "{{ domain_name }}"
    deploy_container_cloudflare_email: "{{ cloudflare_email }}"
    deploy_container_cloudflare_api_token: "{{ cloudflare_api_token }}"
    deploy_container_volumes: # Customize or omit
      - /home/{{ ansible_user }}/{{ deploy_container_service_name }}/config:/kavita/config
      - /home/{{ ansible_user }}/{{ deploy_container_service_name }}/books:/books
    deploy_container_env_vars: # Customize or omit
      PUID: "1000"
      PGID: "999"
      TZ: "America/New_York"
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
    deploy_container_labels: # Customize or omit
      - key: "nautical-backup.enable"
        value: "true"

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Mount media drive from NAS
      become: true
      ansible.posix.mount:
        src: //10.0.30.11/Media/media/books
        path: /home/{{ ansible_user }}/kavita/books
        opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
        fstype: cifs
        state: mounted

    - name: Deploy container
      ansible.builtin.include_role:
        name: "{{ root_playbook_dir }}/roles/deploy_container"
...
