---
- name: Homelab Setup
  hosts: all

# Baseline and VM deployment
- import_playbook: baseline/main.yml
- import_playbook: services/docker/main.yml

# Containers
- import_playbook: containers/code-server/main.yml
- import_playbook: containers/cwa/main.yml
- import_playbook: containers/gitea/main.yml
- import_playbook: containers/media/media.yml
- import_playbook: containers/lazylibrarian/main.yml
- import_playbook: containers/ntfy/main.yml.yml
- import_playbook: containers/wbo/main.yml.yml
- import_playbook: containers/plex/main.yml
- import_playbook: containers/uptime-kuma/main.yml
...
