---
- name: Install WBO
  hosts: wbo

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/vars"

    - name: Install WBO
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_key['key'] }}"
        tailscale_container_service_name: wbo
        tailscale_container_image: lovasoa/wbo
        tailscale_container_tag: v1.20.1
        tailscale_container_serve_port: 80
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/wbo/whiteboards:/opt/app/server-data
        tailscale_container_labels:
          nautical-backup.enable: "true"
...
