---
- name: Deploy {{ deploy_container_service_name }}
  hosts: "{{ deploy_container_host_group_name }}"
  vars:
    deploy_container_service_name: # Service/container name
    deploy_container_host_group_name: # Host group for container to be deployed to
    deploy_container_service_image: # Container image -- ex. louislam/uptime-kuma
    deploy_container_service_tag: # Image tag -- ex. latest
    deploy_container_service_port: # Must be quoted -- ex. "80" not 80
    deploy_container_service_scheme: # http or https
    deploy_container_forward_auth: # true or false
    deploy_container_tailnet_name: "{{ tailnet_name }}"
    deploy_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
    deploy_container_domain_name: "{{ domain_name }}"
    deploy_container_cloudflare_email: "{{ cloudflare_email }}"
    deploy_container_cloudflare_api_token: "{{ cloudflare_api_token }}"
    deploy_container_volumes: # Customize or omit
      - /home/{{ ansible_user }}/{{ deploy_container_service_name }}/data:/app/data
    deploy_container_env_vars: # Customize or omit
      PUID: "1000"
      PGID: "999"
    deploy_container_labels: # Customize or omit
      - key: "key-here"
        value: "value here"
      - key: "key-here"
        value: "value here"

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Deploy container
      ansible.builtin.include_role:
        name: "{{ root_playbook_dir }}/roles/deploy_container"
...
