---
- name: Deploy {{ deploy_container_service_name }}
  hosts: "{{ deploy_container_host_group_name }}"
  vars:
    deploy_container_service_name: cwa # Service/container name
    deploy_container_host_group_name: cwa # Host group for container to be deployed to
    deploy_container_service_image: crocodilestick/calibre-web-automated # Container image -- ex. louislam/uptime-kuma
    deploy_container_service_tag: V2.1.2 # Image tag -- ex. latest
    deploy_container_service_port: "8083" # Must be quoted -- ex. "80" not 80
    deploy_container_service_scheme: http # http or https
    deploy_container_forward_auth: true # true or false
    deploy_container_tailnet_name: "{{ tailnet_name }}"
    deploy_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
    deploy_container_domain_name: "{{ domain_name }}"
    deploy_container_cloudflare_email: "{{ cloudflare_email }}"
    deploy_container_cloudflare_api_token: "{{ cloudflare_api_token }}"
    deploy_container_volumes: # Customize or omit
      - /home/{{ ansible_user }}/{{ tailscale_container_service_name }}/config:/config
      - /home/{{ ansible_user }}/{{ tailscale_container_service_name }}/book-ingest:/cwa-book-ingest
      - /home/{{ ansible_user }}/{{ tailscale_container_service_name }}/library:/calibre-library
    deploy_container_env_vars: # Customize or omit
      PUID: "1000"
      PGID: "999"
      TZ: "America/New_York"
      DOCKER_MODS: "linuxserver/mods:universal-calibre"
    deploy_container_labels: # Customize or omit
      - key: "nautical-backup.enable"
        value: "true"

  tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Mount book folder from NAS
      become: true
      ansible.posix.mount:
        src: //10.0.30.10/Media/media/books
        path: /home/{{ ansible_user }}/cwa/books
        opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
        fstype: cifs
        state: mounted

    - name: Copy booksync script to server
      ansible.builtin.copy:
        src: booksync.sh
        dest: /home/{{ ansible_user }}/cwa/booksync.sh
        owner: "{{ ansible_user }}"
        group: docker
        mode: '0755'

    - name: Enable cron job to sync books to ingest folder
      ansible.builtin.cron:
        name: "cwa booksync"
        minute: "0"
        hour: "8,16"
        job: "/home/{{ ansible_user }}/cwa/booksync.sh"

    - name: Deploy container
      ansible.builtin.include_role:
        name: "{{ root_playbook_dir }}/roles/deploy_container"
...
