---
- name: Install Calibre and Calibre-Web
  hosts: calibre

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Mount media drive from NAS
      become: true
      ansible.posix.mount:
        src: //10.0.30.10/Media
        path: /home/josh/media
        opts: "rw,vers=3,username={{ truenas_username }},password={{ truenas_password }},uid=1000,gid=999"
        fstype: cifs
        state: mounted

    - name: Install calibre
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: calibre
        tailscale_container_image: lscr.io/linuxserver/calibre
        tailscale_container_tag: latest
        tailscale_container_serve_port: 8080
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/calibre/config:/config
        tailscale_container_env_vars:
          PUID: "1000"
          PGID: "999"
          TZ: "America/New_York"
        tailscale_container_labels:
          nautical-backup.enable: "true"

    - name: Install calibre-web
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: calibre-web
        tailscale_container_image: lscr.io/linuxserver/calibre-web
        tailscale_container_tag: arm64v8-0.6.22
        tailscale_container_serve_port: 8083
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/calibre-web/config:/config
          - /home/{{ ansible_user }}/calibre/config/books:/books
        tailscale_container_env_vars:
          PUID: "1000"
          PGID: "999"
          TZ: "America/New_York"
        tailscale_container_labels:
          nautical-backup.enable: "true"
...
