---
- name: Install and configure VS Code Server
  hosts: code_server
  
  tasks:
  - name: Include variables
    ansible.builtin.include_vars:
      dir: "{{ playbook_dir }}/vars"

  - name: Install code-server
    ansible.builtin.include_role:
      name: joshrnoll.homelab.tailscale_container
    vars:
      tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_key['key'] }}"
      tailscale_container_service_name: code-server
      tailscale_container_image: linuxserver/code-server
      tailscale_container_tag: "4.90.3"
      tailscale_container_serve_port: 8443
      tailscale_container_volumes:
        - /home/{{ ansible_user }}/{{ service_name }}/config:/config
      tailscale_container_env_vars:
        PUID: "1000"
        PGID: "999"
        PROXY_DOMAIN: code-server.mink-pirate.ts.net
        TZ: America/New_York
        PASSWORD: "{{ CODE_SERVER_PASS }}"
        SUDO_PASSWORD: "{{ CODE_SERVER_PASS }}"
      tailscale_container_labels: 
        nautical-backup.enable: "true"
...