---
- name: Deploy {{ service_name }}
  hosts: nginx
  vars:
    service_name: nginx
    service_image: nginx
    service_tag: latest

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Define container labels
      ansible.builtin.set_fact:
        container_labels:
          traefik.enable: "true"
          traefik.http.routers.{{ service_name }}.rule: "Host(`{{ service_name }}.{{ domain_name }}`)"
          traefik.http.routers.{{ service_name }}.entrypoints: "https"
          traefik.http.routers.{{ service_name }}.tls: "true"
          traefik.http.routers.{{ service_name }}.tls.certresolver: "cloudflare"
          traefik.http.routers.{{ service_name }}.middlewares: "authentik@docker"
          traefik.http.services.{{ service_name }}.loadbalancer.server.scheme: "http"
          traefik.http.services.{{ service_name }}.loadbalancer.server.port: "80"

    - name: Deploy {{ service_name }}
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: "{{ service_name }}"
        tailscale_container_image: "{{ service_image }}"
        tailscale_container_tag: "{{ service_tag }}"
        tailscale_container_no_serve: true
        tailscale_container_userspace_networking: "false"
        tailscale_container_labels: |
          {{ container_labels | ansible.builtin.combine( 
          {'kop.bind.ip': tailscale_container_ip_address, 'kop.bind.ip' : tailscale_container_ip_address}) }}
...
