---
- name: Install ntfy
  hosts: ntfy
  
  tasks:
    - name: Include variables
      ansible.builtin.include_vars: 
        dir: "{{ playbook_dir }}/vars"

    - name: Ensure /home/{{ ansible_user }}/ntfy/etc/ntfy exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/ntfy/etc/ntfy
        state: directory

    - name: Copy server.yml to server
      ansible.builtin.copy:
        src: server.yml
        dest: /home/{{ ansible_user }}/ntfy/etc/ntfy/server.yml
        force: yes

    - name: Add gmail app password to server.yml
      ansible.builtin.lineinfile:
        regexp: '^smtp-sender-pass:'
        line: 'smtp-sender-pass: {{ gmail_app_pass }}'
        path: /home/{{ ansible_user }}/ntfy/etc/ntfy/server.yml
        state: present
    
    - name: Install ntfy
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_key['key'] }}"
        tailscale_container_service_name: ntfy
        tailscale_container_image: binwiederhier/ntfy
        tailscale_container_tag: latest
        tailscale_container_commands: serve
        tailscale_container_serve_port: 80
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/ntfy/var/cache/ntfy:/var/cache/ntfy
          - /home/{{ ansible_user }}/ntfy/etc/ntfy:/etc/ntfy
        tailscale_container_env_vars:
          TZ: "America/New_York"
        tailscale_container_labels: 
          nautical-backup.enable: "true"
...