---
- name: Install ntfy
  hosts: ntfy

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ root_playbook_dir }}/vars"

    - name: Ensure /etc/ntfy exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/ntfy/etc/ntfy
        state: directory
        mode: "0775"

    - name: Template server.yml to server
      ansible.builtin.template:
        src: server.j2
        dest: /home/{{ ansible_user }}/ntfy/etc/ntfy/server.yml        
        mode: "0775"

    - name: Install ntfy
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: ntfy
        tailscale_container_image: binwiederhier/ntfy
        tailscale_container_tag: latest
        tailscale_container_commands: serve
        tailscale_container_serve_port: 80
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/ntfy/var/cache/ntfy:/var/cache/ntfy
          - /home/{{ ansible_user }}/ntfy/etc/ntfy:/etc/ntfy
        tailscale_container_env_vars:
          TZ: "America/New_York"
        tailscale_container_labels:
          nautical-backup.enable: "true"
...
