---
## TODO - Freshrss webui refusing connections
- name: Install FreshRSS
  hosts: freshrss

  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        dir: "{{ vars_dir_path }}/vars"

    - name: Install FreshRSS
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_key['key'] }}"
        tailscale_container_service_name: fresh-rss
        tailscale_container_image: lscr.io/linuxserver/freshrss
        tailscale_container_tag: latest
        tailscale_container_serve_port: 80
        tailscale_container_userspace_networking: "false"
        tailscale_container_public: false
        tailscale_container_labels:
          nautical-backup.enable: "true"
        tailscale_container_volumes:
          - /home/{{ ansible_user }}/fresh-rss/config:/config
        tailscale_container_env_vars:
          PUID: "1000"
          PGID: "999"
          TZ: "America/New_York"
...
