- name: Ensure desired VMs are deployed
  hosts: proxmox_api

  tasks:
    - name: Import variables
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/vars"

    - name: Run role for VM creation
      ansible.builtin.include_role:
        name: joshrnoll.homelab.create_proxmox_vms
      vars: 
        # Proxmox credentials
        create_proxmox_vms_proxmox_username: "{{ proxmox_username }}"
        create_proxmox_vms_proxmox_api_token_id: "{{ proxmox_api_token_id }}"
        create_proxmox_vms_proxmox_api_token_secret: "{{ proxmox_api_token_secret }}"

        # VMs to be created
        create_proxmox_vms_list: "{{ create_proxmox_vms_list }}"
