---
- name: Initial setup for all servers
  hosts: ubuntu,fedora

  tasks:
    - name: Import variables
      ansible.builtin.include_vars:
        dir: "{{ vars_dir_path }}/vars"

    - name: Run server baseline role
      ansible.builtin.include_role:
        name: joshrnoll.homelab.server_baseline
      vars:
        server_baseline_created_username: josh
        server_baseline_tailscale_oauth_client_secret: "{{ tailscale_servers_oauth_client['secret'] }}"
        server_baseline_ubuntu_packages:
          - tmux
        server_baseline_fedora_packages:
          - tmux
...
