---
- name: Pihole ufw configuration
  hosts: pihole
  user: josh

  tasks:
    - name: Open firewall ports
      become: true
      community.general.ufw:
        state: enabled
        rule: allow
        port: "{{ item }}"
        proto: any
      loop:
        - "53"
        - "5335"
        - "80"
...
